sonar.projectKey=AhmedJ561_cohort-9-mern-11867-ahmed
sonar.organization=ahmedj561
sonar.projectName=cohort-9-mern-11867-ahmed
sonar.sources=Frontend/src,Backend/src
sonar.tests=Frontend/tests,Backend/test
sonar.javascript.lcov.reportPaths=Frontend/coverage/lcov.info,Backend/coverage/lcov.info
sonar.exclusions=**/*.test.js,**/*.test.jsx
